### PR TITLE
Updated the logic for escaping special characters

### PR DESCRIPTION
**Pull request by AnshuHanda**
Now I have changed the logic so only "/" character will be escaped if it is there in query parameter.

### CODE REVIEW

**Comment by albingeorge** [comment]
In the query string, this changes "/" to "\/" and "\\" to "\".

Example: 
```
Cirrus i6 - Indoor Pan / Tilt Cloud Security Camera
```
gets converted to
```
Cirrus i6 - Indoor Pan \/ Tilt Cloud Security Camera
```
thus escaping the "/" character.


@AnshuHandam, I understand that "/" needs to be escaped(in Solr) and therefore converting the same to "\/".

Can you explain why we need to convert "\\" to "\"?

**Comment by AnshuHanda** [comment]
@albingeorge we need to escape "\" also.

**Comment by ganeshparsads** [comment]
In healthyplanet canada, for query
Immune Support / Boost ==> Immune Support \/ Boost
it's escaping the forward slash and it's working fine.
But while updating the query in SRP it's showing the escaped query.

**Comment by AnshuHanda** [comment]
@rahulcs I have done git rebase on escape-urls branch . Please review and merge

**Comment by rahulcs** [comment]
This should be handled from search 
Issue filed here: unbxd/issue-tracker#1802

**Pull request closed without merging**
