### PR TITLE
merged old bucketed search code

### PR DESCRIPTION
**Pull request by sharathk2u**
@rahulcs

### CODE REVIEW

**Comment by amarts** [comment]
@rahulcs please look into this.

**Comment by rahulcs** [comment]
@sharathk2u can you indent this code?

**Comment by sharathk2u** [comment]
Okay I will indent.

**Comment by rahulcs** [comment]
@sharathk2u also add documentation in README.md

**Comment by amarts** [comment]
@sharathk2u can you get these issues resolved? I want to see this merged.

**Comment by sharathk2u** [comment]
This can be closed. I will send a new PR.

**Pull request closed without merging**
